name: MMGen_quickstart
channels:
  - https://mirrors.pku.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=hc881cc4_6
  - libgomp=13.2.0=hc881cc4_6
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.45.3=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4.20240210=h59595ed_0
  - openssl=3.2.1=hd590300_1
  - python=3.10.14=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - tk=8.6.13=noxft_h4845f30_101
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.21.0
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - audioread==3.0.1
      - blinker==1.8.2
      - braceexpand==0.1.7
      - build==1.2.1
      - cachecontrol==0.14.0
      - cachetools==5.5.0
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cleo==2.1.0
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - crashtest==0.4.1
      - cryptography==42.0.5
      - cycler==0.12.1
      - datasets==2.1.0
      - debugpy==1.8.5
      - decorator==5.1.1
      - diffusers==0.30.0
      - dill==0.3.8
      - distlib==0.3.8
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - dulwich==0.21.7
      - einops==0.7.0
      - email-validator==2.1.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - faiss-cpu==1.8.0.post1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - fastjsonschema==2.19.1
      - ffmpy==0.3.2
      - filelock==3.13.4
      - flask==3.0.3
      - fonttools==4.51.0
      - frozenlist==1.4.0
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-ai-generativelanguage==0.6.6
      - google-api-core==2.19.1
      - google-api-python-client==2.142.0
      - google-auth==2.34.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.7.2
      - googleapis-common-protos==1.64.0
      - gradio==4.13.0
      - gradio-client==0.8.0
      - grpcio==1.66.0
      - grpcio-status==1.62.3
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.24.6
      - idna==3.4
      - imageio==2.34.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - installer==0.7.0
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipython==8.24.0
      - itsdangerous==2.2.0
      - jaraco-classes==3.4.0
      - jedi==0.19.1
      - jeepney==0.8.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - keyring==24.3.1
      - kiwisolver==1.4.5
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - lazy-loader==0.4
      - librosa==0.8.0
      - lightning-utilities==0.11.2
      - llvmlite==0.41.1
      - markdown-it-py==3.0.0
      - markdown2==2.4.10
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mido==1.3.2
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numba==0.58.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - orjson==3.10.3
      - p-tqdm==1.4.0
      - packaging==23.2
      - pandas==2.2.2
      - parso==0.8.4
      - pathos==0.3.2
      - pexpect==4.9.0
      - pillow==10.1.0
      - pip==23.3.1
      - pkginfo==1.10.0
      - platformdirs==4.0.0
      - poetry==1.8.2
      - poetry-core==1.9.0
      - poetry-plugin-export==1.7.1
      - pooch==1.8.0
      - pox==0.3.4
      - ppft==1.7.6.8
      - pretty-midi==0.2.10
      - prompt-toolkit==3.0.43
      - proto-plus==1.24.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.21
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pyproject-hooks==1.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytorch-lightning==2.2.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.1.0
      - rapidfuzz==3.8.1
      - referencing==0.35.1
      - regex==2024.4.16
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - resampy==0.4.2
      - responses==0.18.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.3
      - scikit-image==0.23.2
      - scikit-learn==1.3.2
      - scipy==1.9.3
      - secretstorage==3.3.3
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.0.1
      - setproctitle==1.3.3
      - setuptools==68.2.2
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soxr==0.3.7
      - ssr-eval==0.0.7
      - stack-data==0.6.3
      - starlette==0.37.2
      - style==1.1.0
      - sympy==1.12
      - taming-transformers-rom1504==0.0.6
      - threadpoolctl==3.2.0
      - tifffile==2024.4.24
      - timm==0.4.12
      - tokenizers==0.13.3
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.3.0
      - torchaudio==2.3.0
      - torchlibrosa==0.1.0
      - torchmetrics==1.3.2
      - torchvision==0.18.0
      - tornado==6.4.1
      - tqdm==4.66.2
      - traitlets==5.14.3
      - transformers==4.30.2
      - triton==2.3.0
      - trove-classifiers==2024.4.10
      - typer==0.12.3
      - typing-extensions==4.8.0
      - tzdata==2024.1
      - ujson==5.10.0
      - update==0.0.1
      - uritemplate==4.1.1
      - urllib3==2.1.0
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - virtualenv==20.26.0
      - wandb==0.16.6
      - watchfiles==0.22.0
      - wave==0.0.2
      - wcwidth==0.2.13
      - webdataset==0.2.86
      - websockets==11.0.3
      - werkzeug==3.0.4
      - wget==3.2
      - wheel==0.41.3
      - xlsxwriter==3.1.2
      - xxhash==3.4.1
      - yarl==1.9.2
      - zipp==3.18.1
